message='Rome Total War is a good strategy game.'
message=message.upper()
# message=message.lower()
# message=message.capitalize()
# message=message.title()
# message=message.strip()
# message=message.split()
# message='*'.join(message)
# index=message.find('WAR')
# is_found=message.startswith('R')
# is_found_atEnd=message.endswith('.')
# print(index)
# print(is_found)
# print(is_found_atEnd)
# message=message.replace('ROME','SHOGUN')
message=message.center(200,'/')
print(message)